# config.inc.sh

DROPLET_PROJECT_NAME="${DROPLET_PROJECT_NAME:=Testing ground}"
DROPLET_NAME="${DROPLET_NAME:=ubuntu-testing}"
DROPLET_DOMAIN="${DROPLET_DOMAIN:=uni-alcon.de}"
DROPLET_HOST_NAME="${DROPLET_HOST:=default}"
DROPLET_IMAGE="${DROPLET_IMAGE:=ubuntu-22-04-x64}"
DROPLET_SIZE="${DROPLET_SIZE:=s-1vcpu-512mb-10gb}"
DROPLET_REGION="${DROPLET_REGION:=fra1}"
DROPLET_VPC="${DROPLET_VPC:=4a1aaa56-92b6-41be-b52b-558f1848e369}"
DROPLET_SSH_KEY_NAME="${DO_SSH_KEY_NAME:=Digital Ocean}"
 
# EOF
